name: Run Podsync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Clone Podsync
        run: git clone https://github.com/mxpv/podsync.git

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false  # Desativa o cache automático

      - name: Build Podsync
        run: |
          cd podsync
          go build -o ../podsync-bin ./cmd/podsync

      - name: List files for debugging
        run: ls -la

      - name: Run Podsync
        run: ./podsync-bin --config podsync.json

      - name: Copy feeds to repo
        run: |
          mkdir -p public
          cp -r feeds/* public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public



