name: Run Podsync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Podsync
        run: |
          go build -o podsync-bin ./podsync/cmd/podsync

      - name: List files for debugging
        run: ls -la

      - name: Run Podsync
        run: ./podsync-bin --config podsync.json --token tokens.toml


      - name: Copy feeds to repo
        run: |
          mkdir -p public
          cp -r feeds/* public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public



